import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware'

export const getCancellationState=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=context.supabase as any;const [{data:license},{data:request}]=await Promise.all([db.from('licenses').select('id,status,expires_at,plan_id,plans(name)').eq('user_id',context.userId).eq('status','active').order('expires_at',{ascending:false}).limit(1).maybeSingle(),db.from('subscription_cancellation_requests').select('*').eq('user_id',context.userId).eq('status','requested').order('requested_at',{ascending:false}).limit(1).maybeSingle()]);return {license:license??null,request:request??null}})

export const requestCancellation=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((d:unknown)=>z.object({reason:z.enum(['price','usage','missing','technical','other']),details:z.string().trim().max(800).nullish()}).parse(d)).handler(async({data,context})=>{const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const db=supabaseAdmin as any;const {data:license}=await db.from('licenses').select('id,status,expires_at').eq('user_id',context.userId).eq('status','active').order('expires_at',{ascending:false}).limit(1).maybeSingle();if(!license)throw new Error('Nenhuma assinatura ativa encontrada.');await db.from('subscription_retention_feedback').insert({user_id:context.userId,subscription_id:null,reason:data.reason,details:data.details??null});const {data:existing}=await db.from('subscription_cancellation_requests').select('id').eq('user_id',context.userId).eq('status','requested').maybeSingle();if(existing)return {ok:true as const,already_requested:true,access_until:license.expires_at};const {error}=await db.from('subscription_cancellation_requests').insert({user_id:context.userId,license_id:license.id,reason:data.reason,details:data.details??null,status:'requested'});if(error)throw new Error('Não foi possível registrar seu pedido de cancelamento.');return {ok:true as const,already_requested:false,access_until:license.expires_at}})

export const withdrawCancellation=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const db=supabaseAdmin as any;await db.from('subscription_cancellation_requests').update({status:'withdrawn',updated_at:new Date().toISOString()}).eq('user_id',context.userId).eq('status','requested');return {ok:true as const}})
