import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

export type OrdersSummary={pedidos:number;vendas:number;faturamento_cents:number;ticket_medio_cents:number;cancelamentos:number;series:Array<{date:string;pedidos:number;faturamento_cents:number}>;recentOrders:Array<{id:string;status:string;date_created:string;total_amount_cents:number;buyer_nickname:string|null;items_summary:string;item_id:string|null;item_title:string;quantity:number;image:string|null}>};
export type OrdersResult={ok:true;configured:true;summary:OrdersSummary}|{ok:false;configured:false;reason:string}|{ok:false;configured:true;reason:string};
const inputSchema=z.object({fromISO:z.string(),toISO:z.string()});
function describeOrdersError(reason:string):string{if(reason==="missing_token"||reason==="missing_refresh_token")return "A conexão com o Mercado Livre precisa ser renovada. Reconecte a conta na Central de integrações.";if(reason==="not_configured")return "A integração do Mercado Livre ainda não está configurada no servidor.";if(reason==="missing_ml_user_id")return "Não foi possível identificar a conta vendedora conectada ao Mercado Livre.";if(reason==="orders_search_401")return "O Mercado Livre recusou o acesso aos pedidos porque a autorização não é mais válida. Reconecte a conta.";if(reason==="orders_search_403")return "A conta está conectada, mas o aplicativo não tem permissão para consultar vendas e pedidos.";if(reason.startsWith("orders_search_"))return `O Mercado Livre recusou a consulta de vendas (código ${reason.split("_").pop()}). Tente novamente em alguns minutos.`;return "Não foi possível consultar as vendas no Mercado Livre agora."}
function imageFrom(value:unknown):string|null{if(!Array.isArray(value)||!value.length)return null;const first=value[0] as any;return typeof first==="string"?first:typeof first?.secure_url==="string"?first.secure_url:typeof first?.url==="string"?first.url:null}

export const getOrdersSummary=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((data:unknown)=>inputSchema.parse(data)).handler(async({context,data}):Promise<OrdersResult>=>{
 const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data:connection}=await supabaseAdmin.from("ml_connections").select("connected,ml_user_id").eq("user_id",context.userId).maybeSingle();if(!connection?.connected)return {ok:false,configured:false,reason:"Conta do Mercado Livre não conectada."};
 const {fetchSellerOrders}=await import("@/lib/orders.server");const result=await fetchSellerOrders(context.userId,data.fromISO,data.toISO);if(!result.ok){const configured=result.reason!=="missing_token"&&result.reason!=="not_configured";return {ok:false,configured,reason:describeOrdersError(result.reason)}}
 const orders=result.orders,byDay=new Map<string,{pedidos:number;faturamento_cents:number}>();let faturamento_cents=0,vendas=0,cancelamentos=0;
 for(const order of orders){const day=order.date_created.slice(0,10),entry=byDay.get(day)??{pedidos:0,faturamento_cents:0};entry.pedidos+=1;const cancelled=order.status==="cancelled";if(cancelled)cancelamentos+=1;const amount=Math.round(order.total_amount*100);if(!cancelled){entry.faturamento_cents+=amount;faturamento_cents+=amount;vendas+=order.items.reduce((s,it)=>s+it.quantity,0)}byDay.set(day,entry)}
 const series=Array.from(byDay.entries()).map(([date,v])=>({date,...v})).sort((a,b)=>a.date.localeCompare(b.date));const pedidos=orders.length,ticket_medio_cents=pedidos>0?Math.round(faturamento_cents/Math.max(pedidos-cancelamentos,1)):0;
 const ids=new Set(orders.slice(0,50).flatMap(o=>o.items.map(it=>it.item_id).filter((id):id is string=>!!id)));const {data:localListings}=await supabaseAdmin.from("listings").select("source_ml_id,published_ml_id,images,title").eq("user_id",context.userId).limit(1000);const imageById=new Map<string,string|null>();for(const row of localListings??[]){const image=imageFrom(row.images);if(row.source_ml_id)imageById.set(String(row.source_ml_id),image);if(row.published_ml_id)imageById.set(String(row.published_ml_id),image)}
 const recentOrders=orders.slice(0,50).map(o=>{const first=o.items[0];return {id:o.id,status:o.status,date_created:o.date_created,total_amount_cents:Math.round(o.total_amount*100),buyer_nickname:o.buyer_nickname,items_summary:o.items.map(it=>`${it.quantity}x ${it.title}`).join(", "),item_id:first?.item_id??null,item_title:first?.title??"Produto",quantity:first?.quantity??0,image:first?.item_id&&ids.has(first.item_id)?imageById.get(first.item_id)??null:null}});
 return {ok:true,configured:true,summary:{pedidos,vendas,faturamento_cents,ticket_medio_cents,cancelamentos,series,recentOrders}};
});
