import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowUpRight, Bell, Boxes, Bot, PackagePlus, Search, ShoppingBag, Sparkles, Trophy, WalletCards } from "lucide-react";
import { AppShell } from "@/components/app/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { useProfile } from "@/hooks/useAuth";
import { useLicense, useListings } from "@/hooks/useLicense";
import { getDashboardPlatformMetrics } from "@/lib/dashboard.functions";
import { formatBRL, formatNumber } from "@/lib/format";
import { getSellerGrowthOverview } from "@/lib/seller-growth.functions";
import { getSubscriptionCenter } from "@/lib/subscription-center.functions";

export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Painel do vendedor — ANÚNCIO ML"},{name:"robots",content:"noindex"}]}),component:DashboardPage});

function DashboardPage(){
 const {data:profile}=useProfile();const {data:license}=useLicense();const {data:listings=[]}=useListings();
 const overviewFn=useServerFn(getSellerGrowthOverview),platformFn=useServerFn(getDashboardPlatformMetrics),subscriptionFn=useServerFn(getSubscriptionCenter);
 const {data:overview}=useQuery({queryKey:["seller-growth","dashboard"],queryFn:()=>overviewFn(),staleTime:60000});
 const {data:platform}=useQuery({queryKey:["dashboard-platform-metrics"],queryFn:()=>platformFn(),staleTime:60000});
 const {data:subscription}=useQuery({queryKey:["subscription-center"],queryFn:()=>subscriptionFn(),staleTime:30000});
 const sales=overview?.sales??{orders:0,revenue_cents:0,ticket_cents:0,units:0},champions=(overview as any)?.champions??[];
 const active=listings.filter(l=>l.status==="active").length,optimized=listings.filter(l=>(l.ai_score??0)>0).length;
 const catalogValue=listings.filter(l=>l.status==="active").reduce((sum,l)=>sum+Math.max(0,Number(l.price_cents??0))*Math.max(0,Number(l.stock??0)),0);
 const remaining=overview?.quota.remaining??0,used=(overview?.quota as any)?.used??0,limit=(overview?.quota as any)?.quota??remaining+used,pct=limit?Math.min(100,Math.round((used/limit)*100)):0;
 const createdByPlatform=platform?.created_by_platform??used;
 const isFree=!license&&limit===10;
 const lowFree=isFree&&remaining>0&&remaining<=3;
 const ai=subscription?.ai??{limit:0,used:0,remaining:0};
 const aiPct=ai.limit?Math.min(100,Math.round((ai.used/ai.limit)*100)):0;
 return <AppShell title={`Painel do vendedor${profile?.full_name?` · ${profile.full_name.split(" ")[0]}`:""}`} description="Uma visão rápida da sua operação no Mercado Livre e do que você fez dentro do ANÚNCIO ML." actions={<><Button asChild variant="outline" size="sm"><Link to="/notificacoes" as any><Bell className="mr-2 h-4 w-4"/>Alertas</Link></Button><Button asChild size="sm"><Link to="/buscar"><PackagePlus className="mr-2 h-4 w-4"/>Criar a partir do ML</Link></Button></>}>
  {isFree&&<Card className={`mb-4 ${lowFree?"border-amber-500/40 bg-amber-500/[.05]":"border-primary/25 bg-primary/[.035]"}`}><CardContent className="space-y-3 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Teste grátis por quantidade</p><p className="mt-1 text-xl font-extrabold">{used} de 10 anúncios usados</p></div><Badge variant={lowFree?"destructive":"secondary"}>{remaining} restantes</Badge></div><Progress value={pct}/><p className="text-xs leading-5 text-muted-foreground">Cada anúncio criado ou duplicado pelo ANÚNCIO ML consome 1 unidade. Editar, salvar ou publicar novamente o mesmo rascunho não consome outra unidade.</p>{lowFree&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-500/25 bg-background/70 p-3"><p className="text-sm font-medium">Seu teste está acabando. Assine antes de ficar sem novas criações.</p><Button asChild size="sm"><Link to="/licenca">Ver planos</Link></Button></div>}</CardContent></Card>}
  <div className="relative overflow-hidden rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/[.12] via-card to-card p-5 shadow-sm sm:p-7"><div className="pointer-events-none absolute -right-12 -top-16 h-48 w-48 rounded-full bg-primary/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Badge variant="outline" className="border-primary/30 bg-primary/10 text-primary">VISÃO GERAL</Badge><h2 className="mt-3 text-2xl font-extrabold tracking-tight sm:text-3xl">Sua operação, sem misturar anúncios antigos com o uso da plataforma.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Anúncios já existentes no Mercado Livre entram nos ativos. A métrica de criação abaixo conta somente anúncios que nasceram pelo ANÚNCIO ML.</p></div><Button asChild variant="secondary"><Link to="/crescimento">Abrir Central de crescimento<ArrowUpRight className="ml-2 h-4 w-4"/></Link></Button></div></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Anúncios criados" value={formatNumber(createdByPlatform)} hint="criados ou duplicados pelo ANÚNCIO ML" icon={PackagePlus}/><Metric label="Anúncios ativos" value={formatNumber(active)} hint="inclui os anúncios sincronizados da sua conta" icon={Boxes}/><Metric label="Otimizados por IA" value={formatNumber(optimized)} hint="anúncios que já receberam otimização" icon={Bot}/><Metric label="Valor total em catálogo" value={formatBRL(catalogValue)} hint="preço × estoque dos anúncios ativos carregados no painel" icon={WalletCards}/></div>
  <div className="mt-4 grid gap-4 xl:grid-cols-3"><Card className="overflow-hidden border-primary/25 xl:col-span-2"><CardHeader className="border-b bg-primary/[.035]"><div className="flex items-center justify-between"><CardTitle>Uso de anúncios</CardTitle><Badge variant={pct>=85?"destructive":"secondary"}>{pct}% usado</Badge></div></CardHeader><CardContent className="space-y-4 pt-6"><div className="flex items-end justify-between gap-4"><div><p className="text-4xl font-extrabold tracking-tight">{formatNumber(used)} <span className="text-lg font-medium text-muted-foreground">/ {formatNumber(limit)}</span></p><p className="mt-1 text-sm text-muted-foreground">criações e duplicações utilizadas neste ciclo</p></div><strong className="text-sm text-primary">{formatNumber(remaining)} disponíveis</strong></div><Progress value={pct} className="h-2.5"/><p className="rounded-xl bg-muted/50 p-3 text-xs leading-5 text-muted-foreground">1 anúncio = 1 nova criação ou duplicação feita pela plataforma. Editar o mesmo anúncio quantas vezes precisar não gasta outra unidade. Anúncios antigos do Mercado Livre não consomem a franquia.</p>{pct>=70&&<Button asChild><Link to="/assinatura" as any>Ver upgrade ou comprar extras</Link></Button>}</CardContent></Card><Card><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary"/>Créditos de IA</CardTitle><Badge variant={aiPct>=85?"destructive":"outline"}>{aiPct}%</Badge></div></CardHeader><CardContent className="space-y-4"><div><p className="text-3xl font-extrabold">{formatNumber(ai.used)} <span className="text-base font-medium text-muted-foreground">/ {formatNumber(ai.limit)}</span></p><p className="mt-1 text-xs text-muted-foreground">créditos usados no ciclo/saldo disponível</p></div><Progress value={aiPct}/><p className="text-xs leading-5 text-muted-foreground">Otimizações, sugestões e outras ações de IA usam créditos separados da franquia de anúncios.</p>{ai.limit>0&&ai.remaining<=Math.max(5,Math.ceil(ai.limit*.15))&&<Button asChild size="sm" variant="outline" className="w-full"><Link to="/creditos-ia" as any>Comprar créditos de IA</Link></Button>}</CardContent></Card></div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle>Resumo de vendas</CardTitle></CardHeader><CardContent className="space-y-4"><Row label="Pedidos · 30 dias" value={formatNumber(sales.orders)}/><Row label="Unidades vendidas" value={formatNumber((sales as any).units??sales.orders)}/><Row label="Ticket médio" value={formatBRL(sales.ticket_cents)}/><Row label="Plano atual" value={license?.plan?.name??"Teste grátis"}/><Button asChild variant="outline" className="w-full"><Link to="/vendas">Abrir vendas e pedidos</Link></Button></CardContent></Card><Card><CardHeader><CardTitle>Ações rápidas</CardTitle></CardHeader><CardContent className="grid gap-3"><Quick to="/buscar" icon={Search} label="Buscar e duplicar" description="Traga um anúncio do Mercado Livre para trabalhar."/><Quick to="/anuncios" icon={Sparkles} label="Meus anúncios" description="Edite, crie variações e otimize com IA."/><Quick to="/perguntas" icon={ShoppingBag} label="Perguntas de clientes" description="Responda compradores com sugestão pronta da IA."/><Quick to="/saude-anuncios" icon={Bot} label="Saúde dos anúncios" description="Veja rapidamente o que precisa ser corrigido."/></CardContent></Card></div>
  <Card className="mt-4 overflow-hidden border-primary/20"><CardHeader className="border-b bg-primary/[.03]"><div className="flex items-center gap-2 text-primary"><Trophy className="h-5 w-5"/><CardTitle>Anúncios campeões de venda</CardTitle></div></CardHeader><CardContent className="pt-6">{champions.length?<div className="grid gap-4 md:grid-cols-3">{champions.slice(0,3).map((c:any,i:number)=><div key={c.listing_id??c.ml_item_id??i} className="group overflow-hidden rounded-2xl border bg-card transition-all duration-300 hover:-translate-y-1 hover:border-primary/35 hover:shadow-lg"><div className="flex gap-3 p-3">{c.image?<img src={c.image} alt={c.title} className="h-20 w-20 shrink-0 rounded-xl border bg-white object-contain transition-transform duration-300 group-hover:scale-105"/>:<div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-muted"><ShoppingBag className="h-6 w-6 text-muted-foreground"/></div>}<div className="min-w-0 flex-1"><Badge>#{i+1} campeão</Badge><p className="mt-2 line-clamp-2 text-sm font-semibold">{c.title}</p><p className="mt-1 text-xs text-muted-foreground">{formatNumber(c.units)} vendidos</p><p className="mt-1 font-bold text-primary">{formatBRL(c.revenue_cents)}</p></div></div><Button asChild variant="ghost" className="w-full rounded-none border-t"><Link to="/anuncios">Ver anúncio<ArrowUpRight className="ml-2 h-3.5 w-3.5"/></Link></Button></div>)}</div>:<div className="rounded-2xl border border-dashed p-8 text-center"><Trophy className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-semibold">Seus campeões aparecerão aqui</p><p className="mt-1 text-sm text-muted-foreground">Quando houver vendas sincronizadas, destacaremos os produtos com melhor desempenho e suas imagens reais.</p></div>}</CardContent></Card>
 </AppShell>
}
function Metric({label,value,hint,icon:Icon}:any){return <Card className="group transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-extrabold tracking-tight">{value}</p><p className="mt-1 max-w-[230px] text-xs leading-5 text-muted-foreground">{hint}</p></div><div className="rounded-2xl bg-primary/10 p-2.5 transition-transform duration-300 group-hover:scale-110"><Icon className="h-5 w-5 text-primary"/></div></div></CardContent></Card>}
function Row({label,value}:any){return <div className="flex items-center justify-between gap-3 border-b pb-3 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>}
function Quick({to,label,description,icon:Icon}:any){return <Button asChild variant="outline" className="group h-auto justify-start rounded-2xl p-4 text-left transition-all hover:-translate-y-0.5 hover:border-primary/30"><Link to={to}><span className="mr-3 rounded-xl bg-primary/10 p-2"><Icon className="h-5 w-5 shrink-0 text-primary"/></span><span><strong className="block">{label}</strong><span className="mt-1 block whitespace-normal text-xs font-normal leading-5 text-muted-foreground">{description}</span></span></Link></Button>}
