import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getPlatformFoundation, inviteWorkspaceMember } from "@/lib/platform-operations.functions";
export const Route=createFileRoute("/_authenticated/equipe")({component:TeamPage});
function TeamPage(){const load=useServerFn(getPlatformFoundation),invite=useServerFn(inviteWorkspaceMember);const[data,setData]=useState<any>(null),[email,setEmail]=useState(""),[role,setRole]=useState<"manager"|"operator"|"viewer">("operator"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const refresh=useCallback(async()=>setData(await load()),[load]);useEffect(()=>{void refresh()},[refresh]);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{await invite({data:{email,role}});setEmail("");setMessage("Convite registrado.");await refresh()}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível registrar o convite.")}finally{setBusy(false)}}return <AppShell title="Equipe e permissões" description="Cadastre operadores do ANÚNCIO ML sem compartilhar credenciais do Mercado Livre."><div className="space-y-6"><Card><CardHeader><CardTitle className="text-base">Convidar membro</CardTitle><CardDescription>O convite fica registrado; a ativação de acesso continua separada da autorização OAuth do Mercado Livre.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="flex flex-col gap-3 md:flex-row"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="operador@empresa.com" required/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={role} onChange={e=>setRole(e.target.value as any)}><option value="manager">Gerente</option><option value="operator">Operador</option><option value="viewer">Visualizador</option></select><Button disabled={busy}>{busy?"Salvando...":"Registrar convite"}</Button></form>{message&&<p className="mt-3 text-sm text-muted-foreground">{message}</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Membros</CardTitle></CardHeader><CardContent className="space-y-2">{data?.members?.length?data.members.map((m:any)=><div key={m.id} className="flex items-center justify-between rounded-lg border p-3"><div><div className="font-medium">{m.member_email}</div><div className="text-xs text-muted-foreground">{m.role}</div></div><span className="text-sm text-muted-foreground">{m.status}</span></div>):<p className="text-sm text-muted-foreground">Nenhum membro cadastrado.</p>}</CardContent></Card></div></AppShell>}
