import { createFileRoute,useNavigate } from "@tanstack/react-router";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowRight,CheckCircle2,Link2,Loader2,RefreshCcw,ShoppingBag,Unlink } from "lucide-react";
import { useEffect } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDateTime } from "@/lib/format";
import { disconnectMercadoLivre } from "@/lib/ml.functions";
import { getMercadoLivreConnectionState, syncMercadoLivreCatalog } from "@/lib/ml-sync-fast.functions";
import { openMercadoLivreOAuthStart } from "@/lib/ml-oauth-client";

export const Route=createFileRoute("/_authenticated/integracoes")({validateSearch:(search:Record<string,unknown>)=>{const out:{ml?:string;sync?:string}={};if(typeof search["ml"]==="string")out.ml=search["ml"];if(typeof search["sync"]==="string")out.sync=search["sync"];return out},head:()=>({meta:[{title:"Integrações — ANÚNCIO ML"},{name:"robots",content:"noindex"}]}),component:IntegrationsPage});
const MESSAGES:Record<string,{type:"success"|"info"|"error";text:string}>={connected:{type:"success",text:"Mercado Livre conectado com sucesso."},cancelled:{type:"info",text:"Conexão cancelada."},invalid_callback:{type:"error",text:"Retorno inválido do Mercado Livre. Tente novamente."},invalid_state:{type:"error",text:"Sessão de conexão expirada. Inicie novamente."},state_error:{type:"error",text:"Não foi possível validar a conexão."},not_configured:{type:"error",text:"Integração indisponível no momento."},token_error:{type:"error",text:"A autorização não foi concluída. Tente reconectar."},identity_error:{type:"error",text:"Não foi possível identificar a conta autorizada."},persist_error:{type:"error",text:"Não foi possível salvar a conexão."},start_error:{type:"error",text:"Não foi possível iniciar a conexão."}};
function IntegrationsPage(){const navigate=useNavigate(),qc=useQueryClient(),{ml,sync:syncResult}=Route.useSearch();const fetchConnection=useServerFn(getMercadoLivreConnectionState),sync=useServerFn(syncMercadoLivreCatalog),disconnect=useServerFn(disconnectMercadoLivre);const {data,isLoading,refetch}=useQuery({queryKey:["ml-connection"],queryFn:()=>fetchConnection(),refetchOnWindowFocus:true,staleTime:15000});useEffect(()=>{if(!ml)return;let cancelled=false;void(async()=>{if(ml==="connected"){const refreshed=await refetch();if(cancelled)return;if(refreshed.data?.connection?.connected)toast.success("Mercado Livre conectado com sucesso.",{description:syncResult&&syncResult!=="ok"?`Conta conectada. Sincronização inicial: ${syncResult}.`:"Sua conta está pronta para usar."});else toast.error("A autorização não ficou válida. Reconecte a conta.")}else{const message=MESSAGES[ml];if(message)toast[message.type](message.text)}if(!cancelled)navigate({to:"/integracoes",replace:true,search:{}})})();return()=>{cancelled=true}},[ml,syncResult,navigate,refetch]);const syncMl=useMutation({mutationFn:()=>sync(),onSuccess:r=>{if(r.ok)toast.success(`Sincronização concluída: ${r.total} anúncios.`,{description:`${r.imported} novos · ${r.updated} atualizados`});else toast.error("Não foi possível sincronizar.",{description:r.reason});void qc.invalidateQueries({queryKey:["ml-connection"]});void qc.invalidateQueries({queryKey:["listings"]});void qc.invalidateQueries({queryKey:["seller-growth"]})},onError:(error)=>toast.error("Falha ao sincronizar anúncios.",{description:error instanceof Error?error.message:undefined})});const disconnectMl=useMutation({mutationFn:()=>disconnect(),onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:["ml-connection"]}),qc.invalidateQueries({queryKey:["seller-growth"]})]);toast.success("Conta Mercado Livre desconectada.")},onError:()=>toast.error("Falha ao desconectar.")});const connection=data?.connection??null,connected=connection?.connected===true;if(isLoading)return <AppShell title="Integrações"><Skeleton className="h-64 w-full max-w-3xl"/></AppShell>;
 return <AppShell title="Integrações" description="A autorização do Mercado Livre é validada pelo token real da sua conta."><div className="mx-auto max-w-3xl"><Card className="overflow-hidden border-primary/20"><CardHeader className="flex flex-row items-center justify-between border-b bg-primary/[.035]"><CardTitle className="flex items-center gap-2"><span className="rounded-xl bg-primary/10 p-2"><ShoppingBag className="h-5 w-5 text-primary"/></span>Mercado Livre</CardTitle>{connected?<Badge className="bg-emerald-500/15 text-emerald-600"><CheckCircle2 className="mr-1 h-3.5 w-3.5"/>Conectado</Badge>:<Badge variant="destructive">Não conectado</Badge>}</CardHeader><CardContent className="pt-6">{connected?<><div className="grid gap-3 sm:grid-cols-3"><Info label="Conta" value={`@${connection?.nickname??"vendedor"}`}/><Info label="Anúncios sincronizados" value={String(connection?.listings_count??0)}/><Info label="Última sincronização" value={formatDateTime(connection?.last_sync_at??null)}/></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>navigate({to:"/buscar"})}>Buscar e clonar<ArrowRight className="ml-2 h-4 w-4"/></Button><Button variant="outline" disabled={syncMl.isPending} onClick={()=>syncMl.mutate()}>{syncMl.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCcw className="mr-2 h-4 w-4"/>}{syncMl.isPending?"Sincronizando catálogo...":"Sincronizar agora"}</Button><Button variant="ghost" className="text-destructive" disabled={disconnectMl.isPending||syncMl.isPending} onClick={()=>disconnectMl.mutate()}>{disconnectMl.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Unlink className="mr-2 h-4 w-4"/>}Desconectar</Button></div><p className="mt-5 rounded-xl bg-muted/50 p-3 text-xs leading-5 text-muted-foreground">A sincronização atualiza o catálogo existente em lotes. Anúncios trazidos apenas pela sincronização não consomem sua franquia de criação ou clonagem.</p></>:<div className="py-4 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10"><Link2 className="h-6 w-6 text-primary"/></div><h3 className="mt-4 text-lg font-bold">Conecte sua conta do Mercado Livre</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">A conexão é feita pelo acesso oficial do Mercado Livre. Sua senha nunca é informada ao ANÚNCIO ML.</p><Button className="mt-5" onClick={openMercadoLivreOAuthStart}><Link2 className="mr-2 h-4 w-4"/>Conectar Mercado Livre</Button></div>}</CardContent></Card></div></AppShell>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-muted/20 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value}</p></div>}
