import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createProductKit, getPlatformFoundation } from "@/lib/platform-operations.functions";
export const Route=createFileRoute("/_authenticated/kits")({component:KitsPage});
function KitsPage(){
 const load=useServerFn(getPlatformFoundation),createKit=useServerFn(createProductKit);const[data,setData]=useState<any>(null),[name,setName]=useState(""),[sku,setSku]=useState(""),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const refresh=useCallback(async()=>setData(await load()),[load]);useEffect(()=>{void refresh()},[refresh]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function submit(e:FormEvent){e.preventDefault();if(selected.length<1)return;setBusy(true);setMessage("");try{await createKit({data:{name,sku:sku||undefined,listingIds:selected}});setName("");setSku("");setSelected([]);setMessage("Kit criado com segurança no ANÚNCIO ML.");await refresh()}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível criar o kit.")}finally{setBusy(false)}}
 return <AppShell title="Kits de produtos" description="Agrupe anúncios internos e registre a composição antes de qualquer sincronização externa."><div className="space-y-6"><Card><CardHeader><CardTitle className="text-base">Criar kit</CardTitle><CardDescription>Selecione de 1 a 50 anúncios. Criar o kit não publica nem altera estoque no Mercado Livre.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do kit" minLength={2} required/><Input value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU interno (opcional)"/></div><div className="max-h-72 space-y-2 overflow-auto rounded-xl border p-3">{data?.listings?.length?data.listings.map((l:any)=><label key={l.id} className="flex cursor-pointer items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={selected.includes(l.id)} onChange={()=>toggle(l.id)}/><span className="min-w-0"><span className="block truncate text-sm font-medium">{l.title}</span><span className="text-xs text-muted-foreground">{l.ml_id||"Rascunho interno"} · {l.status}</span></span></label>):<p className="text-sm text-muted-foreground">Nenhum anúncio disponível para compor kits.</p>}</div><div className="flex items-center gap-3"><Button disabled={busy||selected.length<1}>{busy?"Criando...":`Criar kit (${selected.length})`}</Button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div></form></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Kits cadastrados</CardTitle><CardDescription>Composição interna e auditável.</CardDescription></CardHeader><CardContent className="space-y-2">{data?.kits?.length?data.kits.map((k:any)=><div key={k.id} className="rounded-lg border p-3"><div className="font-medium">{k.name}</div><div className="text-xs text-muted-foreground">{k.component_listing_ids?.length??0} componentes · {k.enabled?"ativo":"desativado"}</div></div>):<p className="text-sm text-muted-foreground">Nenhum kit cadastrado.</p>}</CardContent></Card></div></AppShell>}
