import { createFileRoute, Link } from '@tanstack/react-router'
import { Bell, Package, Sparkles, TrendingDown, Zap } from 'lucide-react'
export const Route=createFileRoute('/_authenticated/notificacoes')({component:Notificacoes})
const alerts=[
 {icon:Zap,title:'Limite do plano',text:'Avisos de consumo aparecem em 70%, 85% e 100%, com opção de upgrade ou pacote extra.',to:'/creditos'},
 {icon:Package,title:'Estoque e anúncios',text:'Estoque baixo, anúncio pausado e cadastro incompleto viram oportunidades acionáveis.',to:'/crescimento'},
 {icon:TrendingDown,title:'Desempenho',text:'Quedas relevantes de vendas e anúncios abaixo da média podem gerar alerta quando houver dados reais.',to:'/dashboard'},
 {icon:Sparkles,title:'Oportunidades com IA',text:'Sugestões de otimização respeitam os créditos de IA do seu plano.',to:'/crescimento'},
]
function Notificacoes(){return <main className="mx-auto max-w-5xl space-y-6 p-4 md:p-8"><header><p className="text-sm font-semibold text-yellow-400">CENTRAL INTELIGENTE</p><h1 className="mt-1 text-3xl font-bold text-white">Notificações e oportunidades</h1><p className="mt-2 text-zinc-400">A plataforma destaca o que merece sua atenção sem executar ações irreversíveis sozinha.</p></header><div className="grid gap-3">{alerts.map(({icon:Icon,title,text,to})=><article key={title} className="flex flex-col gap-4 rounded-2xl border border-zinc-800 bg-zinc-950 p-5 sm:flex-row sm:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-yellow-400/10"><Icon className="text-yellow-400"/></div><div className="flex-1"><h2 className="font-semibold text-white">{title}</h2><p className="mt-1 text-sm text-zinc-400">{text}</p></div><Link to={to as any} className="rounded-xl border border-zinc-700 px-4 py-2 text-center text-sm font-semibold text-white">Ver agora</Link></article>)}</div><div className="rounded-2xl border border-yellow-400/20 bg-yellow-400/5 p-5"><div className="flex items-center gap-2 font-semibold text-white"><Bell className="text-yellow-400"/>Alertas úteis, não spam</div><p className="mt-2 text-sm text-zinc-400">Preferências de notificação ficam separadas por cota, vendas, estoque e oportunidades.</p></div></main>}
