import { createFileRoute } from "@tanstack/react-router";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Loader2,MessageCircleQuestion,Package,Send,Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { useListings } from "@/hooks/useLicense";
import { formatDateTime } from "@/lib/format";
import { getProductImage } from "@/lib/product-image";
import { answerSellerQuestion,listSellerQuestions,suggestQuestionAnswer,type MlQuestion } from "@/lib/ml-questions.functions";

export const Route=createFileRoute("/_authenticated/perguntas")({head:()=>({meta:[{title:"Perguntas dos clientes — ANÚNCIO ML"},{name:"robots",content:"noindex"}]}),component:QuestionsPage});
function QuestionsPage(){const listFn=useServerFn(listSellerQuestions),answerFn=useServerFn(answerSellerQuestion),suggestFn=useServerFn(suggestQuestionAnswer),qc=useQueryClient();const {data:listings=[]}=useListings();const {data,isLoading,error}=useQuery({queryKey:["ml-questions"],queryFn:()=>listFn(),refetchInterval:60000});const questions=data?.questions??[],unanswered=questions.filter(q=>q.status==="UNANSWERED");const findListing=(itemId:string)=>(listings as any[]).find(l=>l.source_ml_id===itemId||l.published_ml_id===itemId)??null;
 return <AppShell title="Perguntas e atendimento" description="Veja o produto, entenda a dúvida e use a IA para preparar uma resposta antes de enviar ao Mercado Livre."><div className="mb-4 grid gap-3 sm:grid-cols-3"><Metric label="Recebidas" value={data?.total??questions.length}/><Metric label="Sem resposta" value={unanswered.length}/><Metric label="Respondidas" value={questions.filter(q=>q.status==="ANSWERED").length}/></div>{isLoading?<Card><CardContent className="py-10 text-center text-sm text-muted-foreground"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin"/>Carregando perguntas…</CardContent></Card>:error?<Card><CardContent className="py-10 text-center"><p className="font-semibold">Não foi possível carregar as perguntas.</p><p className="mt-1 text-sm text-muted-foreground">{error instanceof Error?error.message:"Confira a conexão com o Mercado Livre."}</p></CardContent></Card>:questions.length===0?<Card><CardContent className="py-12 text-center"><MessageCircleQuestion className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-semibold">Nenhuma pergunta encontrada.</p></CardContent></Card>:<div className="grid gap-3 xl:grid-cols-2">{questions.map(q=><QuestionCard key={q.id} question={q} listing={findListing(q.item_id)} answerFn={answerFn as any} suggestFn={suggestFn as any} afterSend={()=>qc.invalidateQueries({queryKey:["ml-questions"]})}/>)}</div>}</AppShell>}
function QuestionCard({question,listing,answerFn,suggestFn,afterSend}:{question:MlQuestion;listing:any;answerFn:(args:any)=>Promise<any>;suggestFn:(args:any)=>Promise<any>;afterSend:()=>void}){const [text,setText]=useState(question.answer?.text??"");const answered=question.status==="ANSWERED",image=getProductImage(listing?.images);const suggest=useMutation({mutationFn:()=>suggestFn({data:{question_id:question.id,item_id:question.item_id,question:question.text}}),onSuccess:(result:any)=>{if(!result.ok){toast.error(result.reason);return}setText(result.suggestion.answer);toast.success("Sugestão da IA pronta",{description:`Confiança ${result.suggestion.confidence}`})},onError:()=>toast.error("Não foi possível gerar a sugestão")});const send=useMutation({mutationFn:()=>answerFn({data:{question_id:question.id,text:text.trim()}}),onSuccess:()=>{toast.success("Resposta enviada ao Mercado Livre");afterSend()},onError:e=>toast.error(e instanceof Error?e.message:"Falha ao responder")});return <Card className="overflow-hidden transition-all duration-300 hover:border-primary/25 hover:shadow-md"><CardContent className="space-y-4 pt-5"><div className="flex gap-3">{image?<img src={image} alt={listing?.title??question.item_id} className="h-16 w-16 shrink-0 rounded-xl border bg-white object-contain"/>:<div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-xl bg-muted"><Package className="h-5 w-5 text-muted-foreground"/></div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="line-clamp-2 text-sm font-semibold">{listing?.title??"Produto do Mercado Livre"}</p><p className="mt-1 text-[11px] text-muted-foreground">{question.item_id} · {formatDateTime(question.date_created)}</p></div><Badge variant={answered?"default":"secondary"}>{answered?"Respondida":"Aguardando"}</Badge></div></div></div><div className="rounded-2xl bg-muted/50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Pergunta do cliente</p><p className="mt-2 text-sm leading-6">{question.text}</p></div><Textarea rows={4} disabled={answered} value={text} onChange={e=>setText(e.target.value)} placeholder="Digite sua resposta ou peça uma sugestão à IA…" maxLength={2000}/><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-muted-foreground">{text.length}/2000 caracteres</span>{!answered&&<div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>suggest.mutate()} disabled={suggest.isPending}>{suggest.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Sparkles className="mr-2 h-4 w-4"/>}Sugerir com IA</Button><Button size="sm" onClick={()=>send.mutate()} disabled={send.isPending||!text.trim()}>{send.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Send className="mr-2 h-4 w-4"/>}Enviar</Button></div>}</div></CardContent></Card>}
function Metric({label,value}:{label:string;value:number}){return <Card className="transition-all duration-300 hover:border-primary/25"><CardContent className="pt-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p></CardContent></Card>}
