/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminComercialRouteImport } from './routes/_authenticated/admin-comercial'
import { Route as AuthenticatedAdminControleRouteImport } from './routes/_authenticated/admin-controle'
import { Route as AuthenticatedAdminCreditosRouteImport } from './routes/_authenticated/admin-creditos'
import { Route as AuthenticatedAdminRevendedoresRouteImport } from './routes/_authenticated/admin-revendedores'
import { Route as AuthenticatedAnunciosRouteImport } from './routes/_authenticated/anuncios'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedCancelamentoRouteImport } from './routes/_authenticated/cancelamento'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedCreditosIaRouteImport } from './routes/_authenticated/creditos-ia'
import { Route as AuthenticatedCrescimentoRouteImport } from './routes/_authenticated/crescimento'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEncalhadosRouteImport } from './routes/_authenticated/encalhados'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedInteligenciaRouteImport } from './routes/_authenticated/inteligencia'
import { Route as AuthenticatedLicencaRouteImport } from './routes/_authenticated/licenca'
import { Route as AuthenticatedMercadoRouteImport } from './routes/_authenticated/mercado'
import { Route as AuthenticatedMlStartRouteImport } from './routes/_authenticated/ml-start'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedPalavrasChaveRouteImport } from './routes/_authenticated/palavras-chave'
import { Route as AuthenticatedPerguntasRouteImport } from './routes/_authenticated/perguntas'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'
import { Route as AuthenticatedRevendedorRouteImport } from './routes/_authenticated/revendedor'
import { Route as AuthenticatedSaudeAnunciosRouteImport } from './routes/_authenticated/saude-anuncios'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as AuthenticatedEditorIdRouteImport } from './routes/_authenticated/editor.$id'
import { Route as ApiPublicMlCallbackRouteImport } from './routes/api/public/ml/callback'
import { Route as ApiPublicWebhooksMercadolivreRouteImport } from './routes/api/public/webhooks/mercadolivre'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminComercialRoute =
  AuthenticatedAdminComercialRouteImport.update({
    id: '/admin-comercial',
    path: '/admin-comercial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminControleRoute =
  AuthenticatedAdminControleRouteImport.update({
    id: '/admin-controle',
    path: '/admin-controle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCreditosRoute =
  AuthenticatedAdminCreditosRouteImport.update({
    id: '/admin-creditos',
    path: '/admin-creditos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRevendedoresRoute =
  AuthenticatedAdminRevendedoresRouteImport.update({
    id: '/admin-revendedores',
    path: '/admin-revendedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnunciosRoute = AuthenticatedAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCancelamentoRoute =
  AuthenticatedCancelamentoRouteImport.update({
    id: '/cancelamento',
    path: '/cancelamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditosIaRoute = AuthenticatedCreditosIaRouteImport.update({
  id: '/creditos-ia',
  path: '/creditos-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrescimentoRoute =
  AuthenticatedCrescimentoRouteImport.update({
    id: '/crescimento',
    path: '/crescimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEncalhadosRoute = AuthenticatedEncalhadosRouteImport.update({
  id: '/encalhados',
  path: '/encalhados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaRoute =
  AuthenticatedInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLicencaRoute = AuthenticatedLicencaRouteImport.update({
  id: '/licenca',
  path: '/licenca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMercadoRoute = AuthenticatedMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMlStartRoute = AuthenticatedMlStartRouteImport.update({
  id: '/ml-start',
  path: '/ml-start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPalavrasChaveRoute =
  AuthenticatedPalavrasChaveRouteImport.update({
    id: '/palavras-chave',
    path: '/palavras-chave',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerguntasRoute = AuthenticatedPerguntasRouteImport.update({
  id: '/perguntas',
  path: '/perguntas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevendedorRoute = AuthenticatedRevendedorRouteImport.update({
  id: '/revendedor',
  path: '/revendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaudeAnunciosRoute =
  AuthenticatedSaudeAnunciosRouteImport.update({
    id: '/saude-anuncios',
    path: '/saude-anuncios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorIdRoute = AuthenticatedEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMlCallbackRoute = ApiPublicMlCallbackRouteImport.update({
  id: '/api/public/ml/callback',
  path: '/api/public/ml/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadolivreRoute =
  ApiPublicWebhooksMercadolivreRouteImport.update({
    id: '/api/public/webhooks/mercadolivre',
    path: '/api/public/webhooks/mercadolivre',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-comercial': typeof AuthenticatedAdminComercialRoute
  '/admin-controle': typeof AuthenticatedAdminControleRoute
  '/admin-creditos': typeof AuthenticatedAdminCreditosRoute
  '/admin-revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/cancelamento': typeof AuthenticatedCancelamentoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/creditos-ia': typeof AuthenticatedCreditosIaRoute
  '/crescimento': typeof AuthenticatedCrescimentoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/encalhados': typeof AuthenticatedEncalhadosRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/licenca': typeof AuthenticatedLicencaRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/ml-start': typeof AuthenticatedMlStartRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/palavras-chave': typeof AuthenticatedPalavrasChaveRoute
  '/perguntas': typeof AuthenticatedPerguntasRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/revendedor': typeof AuthenticatedRevendedorRoute
  '/saude-anuncios': typeof AuthenticatedSaudeAnunciosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/api/public/ml/callback': typeof ApiPublicMlCallbackRoute
  '/api/public/webhooks/mercadolivre': typeof ApiPublicWebhooksMercadolivreRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-comercial': typeof AuthenticatedAdminComercialRoute
  '/admin-controle': typeof AuthenticatedAdminControleRoute
  '/admin-creditos': typeof AuthenticatedAdminCreditosRoute
  '/admin-revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/cancelamento': typeof AuthenticatedCancelamentoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/creditos-ia': typeof AuthenticatedCreditosIaRoute
  '/crescimento': typeof AuthenticatedCrescimentoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/encalhados': typeof AuthenticatedEncalhadosRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/licenca': typeof AuthenticatedLicencaRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/ml-start': typeof AuthenticatedMlStartRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/palavras-chave': typeof AuthenticatedPalavrasChaveRoute
  '/perguntas': typeof AuthenticatedPerguntasRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/revendedor': typeof AuthenticatedRevendedorRoute
  '/saude-anuncios': typeof AuthenticatedSaudeAnunciosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout': typeof CheckoutIndexRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/api/public/ml/callback': typeof ApiPublicMlCallbackRoute
  '/api/public/webhooks/mercadolivre': typeof ApiPublicWebhooksMercadolivreRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-comercial': typeof AuthenticatedAdminComercialRoute
  '/_authenticated/admin-controle': typeof AuthenticatedAdminControleRoute
  '/_authenticated/admin-creditos': typeof AuthenticatedAdminCreditosRoute
  '/_authenticated/admin-revendedores': typeof AuthenticatedAdminRevendedoresRoute
  '/_authenticated/anuncios': typeof AuthenticatedAnunciosRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/cancelamento': typeof AuthenticatedCancelamentoRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/creditos-ia': typeof AuthenticatedCreditosIaRoute
  '/_authenticated/crescimento': typeof AuthenticatedCrescimentoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/encalhados': typeof AuthenticatedEncalhadosRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/_authenticated/licenca': typeof AuthenticatedLicencaRoute
  '/_authenticated/mercado': typeof AuthenticatedMercadoRoute
  '/_authenticated/ml-start': typeof AuthenticatedMlStartRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/palavras-chave': typeof AuthenticatedPalavrasChaveRoute
  '/_authenticated/perguntas': typeof AuthenticatedPerguntasRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
  '/_authenticated/revendedor': typeof AuthenticatedRevendedorRoute
  '/_authenticated/saude-anuncios': typeof AuthenticatedSaudeAnunciosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/_authenticated/editor/$id': typeof AuthenticatedEditorIdRoute
  '/api/public/ml/callback': typeof ApiPublicMlCallbackRoute
  '/api/public/webhooks/mercadolivre': typeof ApiPublicWebhooksMercadolivreRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/admin-comercial'
    | '/admin-controle'
    | '/admin-creditos'
    | '/admin-revendedores'
    | '/anuncios'
    | '/assinatura'
    | '/automacoes'
    | '/buscar'
    | '/cancelamento'
    | '/conta'
    | '/creditos'
    | '/creditos-ia'
    | '/crescimento'
    | '/dashboard'
    | '/encalhados'
    | '/estoque'
    | '/indicacoes'
    | '/integracoes'
    | '/inteligencia'
    | '/licenca'
    | '/mercado'
    | '/ml-start'
    | '/notificacoes'
    | '/onboarding'
    | '/oportunidades'
    | '/palavras-chave'
    | '/perguntas'
    | '/precificacao'
    | '/relatorios'
    | '/resultados'
    | '/revendedor'
    | '/saude-anuncios'
    | '/vendas'
    | '/admin/login'
    | '/auth/callback'
    | '/checkout/success'
    | '/checkout/'
    | '/editor/$id'
    | '/api/public/ml/callback'
    | '/api/public/webhooks/mercadolivre'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/admin-comercial'
    | '/admin-controle'
    | '/admin-creditos'
    | '/admin-revendedores'
    | '/anuncios'
    | '/assinatura'
    | '/automacoes'
    | '/buscar'
    | '/cancelamento'
    | '/conta'
    | '/creditos'
    | '/creditos-ia'
    | '/crescimento'
    | '/dashboard'
    | '/encalhados'
    | '/estoque'
    | '/indicacoes'
    | '/integracoes'
    | '/inteligencia'
    | '/licenca'
    | '/mercado'
    | '/ml-start'
    | '/notificacoes'
    | '/onboarding'
    | '/oportunidades'
    | '/palavras-chave'
    | '/perguntas'
    | '/precificacao'
    | '/relatorios'
    | '/resultados'
    | '/revendedor'
    | '/saude-anuncios'
    | '/vendas'
    | '/admin/login'
    | '/auth/callback'
    | '/checkout/success'
    | '/checkout'
    | '/editor/$id'
    | '/api/public/ml/callback'
    | '/api/public/webhooks/mercadolivre'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/admin-comercial'
    | '/_authenticated/admin-controle'
    | '/_authenticated/admin-creditos'
    | '/_authenticated/admin-revendedores'
    | '/_authenticated/anuncios'
    | '/_authenticated/assinatura'
    | '/_authenticated/automacoes'
    | '/_authenticated/buscar'
    | '/_authenticated/cancelamento'
    | '/_authenticated/conta'
    | '/_authenticated/creditos'
    | '/_authenticated/creditos-ia'
    | '/_authenticated/crescimento'
    | '/_authenticated/dashboard'
    | '/_authenticated/encalhados'
    | '/_authenticated/estoque'
    | '/_authenticated/indicacoes'
    | '/_authenticated/integracoes'
    | '/_authenticated/inteligencia'
    | '/_authenticated/licenca'
    | '/_authenticated/mercado'
    | '/_authenticated/ml-start'
    | '/_authenticated/notificacoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/oportunidades'
    | '/_authenticated/palavras-chave'
    | '/_authenticated/perguntas'
    | '/_authenticated/precificacao'
    | '/_authenticated/relatorios'
    | '/_authenticated/resultados'
    | '/_authenticated/revendedor'
    | '/_authenticated/saude-anuncios'
    | '/_authenticated/vendas'
    | '/admin/login'
    | '/auth/callback'
    | '/checkout/success'
    | '/checkout/'
    | '/_authenticated/editor/$id'
    | '/api/public/ml/callback'
    | '/api/public/webhooks/mercadolivre'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ApiPublicMlCallbackRoute: typeof ApiPublicMlCallbackRoute
  ApiPublicWebhooksMercadolivreRoute: typeof ApiPublicWebhooksMercadolivreRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-comercial': {
      id: '/_authenticated/admin-comercial'
      path: '/admin-comercial'
      fullPath: '/admin-comercial'
      preLoaderRoute: typeof AuthenticatedAdminComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-controle': {
      id: '/_authenticated/admin-controle'
      path: '/admin-controle'
      fullPath: '/admin-controle'
      preLoaderRoute: typeof AuthenticatedAdminControleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-creditos': {
      id: '/_authenticated/admin-creditos'
      path: '/admin-creditos'
      fullPath: '/admin-creditos'
      preLoaderRoute: typeof AuthenticatedAdminCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-revendedores': {
      id: '/_authenticated/admin-revendedores'
      path: '/admin-revendedores'
      fullPath: '/admin-revendedores'
      preLoaderRoute: typeof AuthenticatedAdminRevendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios': {
      id: '/_authenticated/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AuthenticatedAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cancelamento': {
      id: '/_authenticated/cancelamento'
      path: '/cancelamento'
      fullPath: '/cancelamento'
      preLoaderRoute: typeof AuthenticatedCancelamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditos-ia': {
      id: '/_authenticated/creditos-ia'
      path: '/creditos-ia'
      fullPath: '/creditos-ia'
      preLoaderRoute: typeof AuthenticatedCreditosIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crescimento': {
      id: '/_authenticated/crescimento'
      path: '/crescimento'
      fullPath: '/crescimento'
      preLoaderRoute: typeof AuthenticatedCrescimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encalhados': {
      id: '/_authenticated/encalhados'
      path: '/encalhados'
      fullPath: '/encalhados'
      preLoaderRoute: typeof AuthenticatedEncalhadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia': {
      id: '/_authenticated/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AuthenticatedInteligenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licenca': {
      id: '/_authenticated/licenca'
      path: '/licenca'
      fullPath: '/licenca'
      preLoaderRoute: typeof AuthenticatedLicencaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mercado': {
      id: '/_authenticated/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof AuthenticatedMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ml-start': {
      id: '/_authenticated/ml-start'
      path: '/ml-start'
      fullPath: '/ml-start'
      preLoaderRoute: typeof AuthenticatedMlStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/palavras-chave': {
      id: '/_authenticated/palavras-chave'
      path: '/palavras-chave'
      fullPath: '/palavras-chave'
      preLoaderRoute: typeof AuthenticatedPalavrasChaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perguntas': {
      id: '/_authenticated/perguntas'
      path: '/perguntas'
      fullPath: '/perguntas'
      preLoaderRoute: typeof AuthenticatedPerguntasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revendedor': {
      id: '/_authenticated/revendedor'
      path: '/revendedor'
      fullPath: '/revendedor'
      preLoaderRoute: typeof AuthenticatedRevendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saude-anuncios': {
      id: '/_authenticated/saude-anuncios'
      path: '/saude-anuncios'
      fullPath: '/saude-anuncios'
      preLoaderRoute: typeof AuthenticatedSaudeAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$id': {
      id: '/_authenticated/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof AuthenticatedEditorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ml/callback': {
      id: '/api/public/ml/callback'
      path: '/api/public/ml/callback'
      fullPath: '/api/public/ml/callback'
      preLoaderRoute: typeof ApiPublicMlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadolivre': {
      id: '/api/public/webhooks/mercadolivre'
      path: '/api/public/webhooks/mercadolivre'
      fullPath: '/api/public/webhooks/mercadolivre'
      preLoaderRoute: typeof ApiPublicWebhooksMercadolivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminComercialRoute: typeof AuthenticatedAdminComercialRoute
  AuthenticatedAdminControleRoute: typeof AuthenticatedAdminControleRoute
  AuthenticatedAdminCreditosRoute: typeof AuthenticatedAdminCreditosRoute
  AuthenticatedAdminRevendedoresRoute: typeof AuthenticatedAdminRevendedoresRoute
  AuthenticatedAnunciosRoute: typeof AuthenticatedAnunciosRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCancelamentoRoute: typeof AuthenticatedCancelamentoRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedCreditosIaRoute: typeof AuthenticatedCreditosIaRoute
  AuthenticatedCrescimentoRoute: typeof AuthenticatedCrescimentoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEncalhadosRoute: typeof AuthenticatedEncalhadosRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedInteligenciaRoute: typeof AuthenticatedInteligenciaRoute
  AuthenticatedLicencaRoute: typeof AuthenticatedLicencaRoute
  AuthenticatedMercadoRoute: typeof AuthenticatedMercadoRoute
  AuthenticatedMlStartRoute: typeof AuthenticatedMlStartRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedPalavrasChaveRoute: typeof AuthenticatedPalavrasChaveRoute
  AuthenticatedPerguntasRoute: typeof AuthenticatedPerguntasRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
  AuthenticatedRevendedorRoute: typeof AuthenticatedRevendedorRoute
  AuthenticatedSaudeAnunciosRoute: typeof AuthenticatedSaudeAnunciosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedEditorIdRoute: typeof AuthenticatedEditorIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminComercialRoute: AuthenticatedAdminComercialRoute,
  AuthenticatedAdminControleRoute: AuthenticatedAdminControleRoute,
  AuthenticatedAdminCreditosRoute: AuthenticatedAdminCreditosRoute,
  AuthenticatedAdminRevendedoresRoute: AuthenticatedAdminRevendedoresRoute,
  AuthenticatedAnunciosRoute: AuthenticatedAnunciosRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCancelamentoRoute: AuthenticatedCancelamentoRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedCreditosIaRoute: AuthenticatedCreditosIaRoute,
  AuthenticatedCrescimentoRoute: AuthenticatedCrescimentoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEncalhadosRoute: AuthenticatedEncalhadosRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedInteligenciaRoute: AuthenticatedInteligenciaRoute,
  AuthenticatedLicencaRoute: AuthenticatedLicencaRoute,
  AuthenticatedMercadoRoute: AuthenticatedMercadoRoute,
  AuthenticatedMlStartRoute: AuthenticatedMlStartRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedPalavrasChaveRoute: AuthenticatedPalavrasChaveRoute,
  AuthenticatedPerguntasRoute: AuthenticatedPerguntasRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
  AuthenticatedRevendedorRoute: AuthenticatedRevendedorRoute,
  AuthenticatedSaudeAnunciosRoute: AuthenticatedSaudeAnunciosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedEditorIdRoute: AuthenticatedEditorIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ApiPublicMlCallbackRoute: ApiPublicMlCallbackRoute,
  ApiPublicWebhooksMercadolivreRoute: ApiPublicWebhooksMercadolivreRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
