// This file is automatically generated. Keep auth compatibility changes minimal.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.manual';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Estes valores são públicos por definição no frontend Supabase. Mantemos um
// fallback para o deploy Lovable continuar autenticando mesmo quando o build não
// injetar as variáveis VITE_*.
const PUBLIC_SUPABASE_URL = 'https://aachxhvpthcszmujjwsq.supabase.co';
const PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_1UJgRP-2Kkg3l4xA2kpptA_4Aywib2B';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readServerEnv(name: 'SUPABASE_URL' | 'SUPABASE_PUBLISHABLE_KEY'): string | undefined {
  if (typeof process === 'undefined' || !process.env) return undefined;
  return process.env[name];
}

function resolveSupabaseConfig() {
  // Preferimos a configuração injetada pelo ambiente. O fallback público existe
  // apenas para o frontend publicado não ficar inutilizável se o Lovable omitir
  // VITE_SUPABASE_* durante o build.
  const url = import.meta.env['VITE_SUPABASE_URL'] || readServerEnv('SUPABASE_URL') || PUBLIC_SUPABASE_URL;
  const key = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || readServerEnv('SUPABASE_PUBLISHABLE_KEY') || PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  return { url, key };
}

export function hasSupabaseBrowserConfig(): boolean {
  const { url, key } = resolveSupabaseConfig();
  return Boolean(url && key);
}

function createSupabaseClient() {
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
